#!/usr/bin/env python3
"""Generate a CycloneDX 1.5 SBOM for ISEC's pinned Python dependencies.

Reads a pip lock/requirements file (default: requirements.lock.txt) that uses
the ``name==version`` form, optionally with ``--hash=sha256:...`` lines, and
emits a CycloneDX 1.5 JSON document.

Standard library only -- no third-party dependencies.

Reproducible output:
  Set SOURCE_DATE_EPOCH to a fixed UNIX timestamp to get a deterministic
  ``metadata.timestamp`` and a content-derived ``serialNumber`` so the SBOM can
  be regenerated byte-for-byte and diffed in CI.

Usage:
  python scripts/generate_sbom.py
  python scripts/generate_sbom.py -i requirements.lock.txt -o sbom/isec-python.cdx.json
"""
from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import os
import re
import sys
import uuid
from pathlib import Path

_REQ_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s\\]+)")
_HASH_RE = re.compile(r"--hash=(sha256|sha512|sha1|md5):([0-9a-fA-F]+)")

_ALG_MAP = {
    "sha256": "SHA-256",
    "sha512": "SHA-512",
    "sha1": "SHA-1",
    "md5": "MD5",
}


def parse_requirements(text):
    """Parse pinned requirements into [{name, version, hashes:[(alg,val)]}]."""
    components = []
    current = None
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("--"):
            # Global flag (e.g. --require-hashes) or a hash line for the
            # component most recently seen.
            if current is not None:
                for alg, val in _HASH_RE.findall(line):
                    current["hashes"].append((alg.lower(), val.lower()))
            continue
        match = _REQ_RE.match(line)
        if match:
            current = {
                "name": match.group(1),
                "version": match.group(2),
                "hashes": [],
            }
            components.append(current)
            for alg, val in _HASH_RE.findall(line):
                current["hashes"].append((alg.lower(), val.lower()))
    return components


def _iso_timestamp():
    epoch = os.environ.get("SOURCE_DATE_EPOCH")
    if epoch:
        try:
            stamp = _dt.datetime.fromtimestamp(int(epoch), tz=_dt.timezone.utc)
            return stamp.strftime("%Y-%m-%dT%H:%M:%SZ"), True
        except (ValueError, OverflowError):
            pass
    now = _dt.datetime.now(tz=_dt.timezone.utc)
    return now.strftime("%Y-%m-%dT%H:%M:%SZ"), False


def _serial(components, deterministic):
    if deterministic:
        digest = hashlib.sha256()
        for comp in sorted(components, key=lambda c: (c["name"], c["version"])):
            digest.update(f"{comp['name']}=={comp['version']}".encode())
            for alg, val in sorted(comp["hashes"]):
                digest.update(f"{alg}:{val}".encode())
        return "urn:uuid:" + str(uuid.UUID(bytes=digest.digest()[:16]))
    return "urn:uuid:" + str(uuid.uuid4())


def build_sbom(components, app_name, app_version, timestamp, serial):
    cdx_components = []
    for comp in components:
        ref = f"pkg:pypi/{comp['name']}@{comp['version']}"
        entry = {
            "type": "library",
            "bom-ref": ref,
            "name": comp["name"],
            "version": comp["version"],
            "purl": ref,
        }
        hashes = [
            {"alg": _ALG_MAP[alg], "content": val}
            for alg, val in comp["hashes"]
            if alg in _ALG_MAP
        ]
        if hashes:
            entry["hashes"] = hashes
        cdx_components.append(entry)

    return {
        "bomFormat": "CycloneDX",
        "specVersion": "1.5",
        "serialNumber": serial,
        "version": 1,
        "metadata": {
            "timestamp": timestamp,
            "tools": [
                {"vendor": "ISEC", "name": "generate_sbom.py", "version": "1.0.0"}
            ],
            "component": {
                "type": "application",
                "bom-ref": f"{app_name}@{app_version}",
                "name": app_name,
                "version": app_version,
            },
        },
        "components": cdx_components,
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate a CycloneDX SBOM.")
    parser.add_argument("--input", "-i", default="requirements.lock.txt")
    parser.add_argument("--output", "-o", default="sbom/isec-python.cdx.json")
    parser.add_argument("--name", default="isec")
    parser.add_argument("--app-version", default="2.0.0")
    args = parser.parse_args(argv)

    input_path = Path(args.input)
    if not input_path.is_file():
        print(f"error: input file not found: {input_path}", file=sys.stderr)
        return 2

    components = parse_requirements(input_path.read_text(encoding="utf-8"))
    if not components:
        print(f"error: no pinned components found in {input_path}", file=sys.stderr)
        return 1

    timestamp, deterministic = _iso_timestamp()
    serial = _serial(components, deterministic)
    sbom = build_sbom(components, args.name, args.app_version, timestamp, serial)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(sbom, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {output_path} ({len(components)} components)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
